---
title: "Company Type Difference Calculations"
author: "Meaghan Brennan"
date: "2024-04-25"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning = FALSE)
library(tidyverse)
library(kableExtra)
library(scales)
library(here)
library(patchwork)
library(RColorBrewer)

```

```{r}

endowment_data <- read_rds(here("data", "endowment_filter_data_990.RDS")) 

companies <- read_csv(here("data", "companies.csv")) %>%
  rename(EIN = ein) %>%
  mutate(EIN = as.character(EIN))

```

```{r}

company_diffs <- companies %>% 
  mutate(Comp_Type = case_when(
    row_number() <= 10 ~ "Opera",
    row_number() <= 20 ~ "Theatre",
    row_number() <= 30 ~ "Symphony",
    row_number() <= 40 ~ "Ballet")) %>% 
  left_join(endowment_data, by = "EIN")


```

```{r}
#calculating means the slow way

mean_opera <- company_diffs %>%
  filter(Comp_Type == "Opera") %>%
  summarize(mean_begin = mean(CYBeginningYearBalanceAmt, na.rm = TRUE), mean_end = mean(CYEndYearBalanceAmt, na.rm = TRUE))

mean_theatre <- company_diffs %>%
  filter(Comp_Type == "Theatre") %>%
  summarize(mean_begin = mean(CYBeginningYearBalanceAmt, na.rm = TRUE), mean_end = mean(CYEndYearBalanceAmt, na.rm = TRUE))

mean_symph <- company_diffs %>%
  filter(Comp_Type == "Symphony") %>%
  summarize(mean_begin = mean(CYBeginningYearBalanceAmt, na.rm = TRUE), mean_end = mean(CYEndYearBalanceAmt, na.rm = TRUE))

mean_ballet <- company_diffs %>%
  filter(Comp_Type == "Ballet") %>%
  summarize(mean_begin = mean(CYBeginningYearBalanceAmt, na.rm = TRUE), mean_end = mean(CYEndYearBalanceAmt, na.rm = TRUE))

```


```{r}

means <- read_csv(here("data", "means_types.csv"))
options(scipen = 999)

beginmeans_plot <- ggplot(means, aes(x = Type, y = Mean_Begin, fill = Type)) + geom_histogram(stat = "identity", position = "dodge") + ylim(0, 140000000)

endmeans_plot <- ggplot(means, aes(x = Type, y = Mean_End, fill = Type)) + geom_histogram(stat = "identity", position = "dodge") + ylim(0, 140000000)

beginmeans_plot / endmeans_plot

```


```{r}

means_wide <- read_csv(here("data", "means_wide.csv"))

means_wide <- means_wide %>% 
  rename("Legend" = when) %>% 
  filter(Legend == "End") %>% 
  select(Type, mean)

means_plot <- ggplot(means_wide, aes(x = Type, y = mean, fill = "Pink1")) + geom_histogram(stat = "identity", position = "stack") + scale_fill_brewer(palette = "Pastel1") + ggtitle("Average Endowment Size at End of Fiscal Years") + xlab("Type Of Company") + ylab("Endowment Balance ($)") + guides(fill = FALSE)
means_plot

ggsave(here('final_report/images/endowment_size_bars.png'))

```


```{r}

endowment_types <- schedule_d %>% 
  rename(BoardDesignated = `/Return/ReturnData/IRS990ScheduleD/BoardDesignatedBalanceEOYPct`, Permanent = `/Return/ReturnData/IRS990ScheduleD/PrmnntEndowmentBalanceEOYPct`, Term = `/Return/ReturnData/IRS990ScheduleD/TermEndowmentBalanceEOYPct`) %>% 
  select(EIN, BoardDesignated, Permanent, Term)

companies_to_ein <- companies_to_ein %>% 
  mutate(Type = case_when(
    row_number() <= 10 ~ "Opera",
    row_number() <= 20 ~ "Theatre",
    row_number() <= 30 ~ "Symphony",
    row_number() <= 40 ~ "Ballet"))

endowment_types_names <- companies_to_ein %>% 
  left_join(endowment_types, by = "EIN")

endowment_types_names$BoardDesignated = as.numeric(as.character(endowment_types_names$BoardDesignated))
endowment_types_names$Permanent = as.numeric(as.character(endowment_types_names$Permanent))
endowment_types_names$Term = as.numeric(as.character(endowment_types_names$Term))

mean_by_endowment_type <- endowment_types_names %>% 
  mutate(BoardDesignated = replace_na(BoardDesignated, 0), 
         Permanent = replace_na(Permanent, 0), 
         Term = replace_na(Term, 0)) %>% 
  group_by(Type) %>% 
  summarize(mean_board = mean(BoardDesignated, na.rm = TRUE), mean_perm = mean(Permanent, na.rm = TRUE), mean_term = mean(Term, na.rm = TRUE)) %>% 
  mutate(mean_board = round((100 * mean_board), digits = 2), mean_perm = round((100 * mean_perm), digits = 2), mean_term = round((100 * mean_term), digits = 2)) %>% 
  mutate(mean_board = paste0(mean_board, "%"), mean_perm = paste0(mean_perm, "%"), mean_term = paste0(mean_term, "%"))



```


```{r}

endowment_lengths <- read_csv(here("data", "endowmentlengths.csv"))

endowment_lengths <- endowment_lengths %>% 
  group_by(Type) %>%
  summarize(Mean_Length = mean(Length, na.rm = TRUE))

```


```{r}

types_means <- read_csv(here("data", "endowment_type_means_wide.csv")) %>% 
  mutate(Mean = as.numeric(sub("%", "", Mean)))

types_plot <- ggplot(types_means, aes(x = Type, y = Mean, fill = Legend)) + geom_histogram(stat = "identity", position = "stack") + scale_fill_brewer(palette = "Pastel1") + ggtitle("Average Endowment Types of Companies") + xlab("Type Of Company") + ylab("Endowment Type (%)")
types_plot

ggsave(here('final_report/images/endowment_type_bars_stack.png'))

types_plot2 <- ggplot(types_means, aes(x = Type, y = Mean, fill = Legend)) + geom_histogram(stat = "identity", position = "dodge") + scale_fill_brewer(palette = "Pastel1") + ggtitle("Average Endowment Types of Companies") + xlab("Type Of Company") + ylab("Endowment Type (%)")
types_plot2

ggsave(here('final_report/images/endowment_type_bars_dodge.png'))

```
```{r}

# finding companies that filed FY23
company_diffs %>% 
  filter(fiscal_year == "2023")
# only Miami City Ballet (592578534)

#budget calcs
budget_info <- read_csv(here("data", "budget_companies.csv")) %>% 
  rename(expense_avg = "Expense Avg", last_expense = "Last Expense")

budgets_by_type <- budget_info %>% 
  group_by(Type) %>% 
  summarize(avg_budget = mean(expense_avg), avg_last_budget = mean(last_expense))


```