---
title: "Explore Endowment Values Over Time"
author: "Chi Qiu"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    df_print: paged
    code_folding: hide
    css: !expr here::here('css', 'template.css')
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "./output_html")})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning = FALSE)
library(tidyverse)
library(kableExtra)
library(scales)
library(plotly)
library(here)
library(glue)

all_plots <- FALSE

```


```{r read data, eval=FALSE}

# starting by only exploring the CY* variables
endowment_data <- read_rds(here("data", 
                                "endowments_by_most_recent_filings.RDS")) 

companies_to_ein <- read_csv(here("data", "companies.csv")) %>%
  mutate(EIN = as.character(ein), organization_name = as.character(Company)) %>%
  select(EIN, organization_name)

```


```{r, eval=FALSE}

endowment_data <- read_rds(here("data", 
                                "endowment_filter_data_990.RDS")) %>%
  select(EIN, fiscal_year, contains("CY"))


# only include EINs that have at least one observation of 
# one of the endowment variables
include_eins <- endowment_data %>%
  pivot_longer(-c(EIN,fiscal_year)) %>%
  group_by(EIN) %>%
  summarize(na_count = sum(is.na(value)),
             total_rows = n()) %>%
  filter(na_count < total_rows) %>%
  pull(EIN) %>% unique()


# taking most recently available information from the CY* variables
# this is to take into account findings from cross referencing that 
# values are not always in correspondence
# when they are in correspondence, this will be equivalent to just taking
# the CY data from each fiscal year 
endowment_data <- endowment_data %>%
  filter(EIN %in% include_eins) %>% 
    group_by(EIN) %>%
    pivot_longer(3: ncol(.),
                 names_to = "variable_name") %>%
    mutate(source = ifelse(grepl("CYM", variable_name),
                           substr(variable_name, 1,4), "CY"),
           # get the year lag from the CYM variable name
           # CYM1 corresponds to 1 year lag
           year_lag = ifelse(grepl("CYM", variable_name), 
                             substr(source, 4,4), 0),
           year_lag = as.numeric(year_lag),
           fiscal_year = as.numeric(paste0(fiscal_year)),
           # get rid of CY or CMX part of the variable name (where X is a year)
           variable_name = gsub("CY|CYM.", "", variable_name)) %>%
    mutate(value_year = fiscal_year -year_lag
           ) %>%
  group_by(EIN, value_year, variable_name) %>%
  arrange(EIN, variable_name, fiscal_year) %>%
  # pick the most recent one available
  slice_max(n = 1, order_by = fiscal_year)  %>%
  select(EIN, value_year, variable_name, source, value) %>%
  rename(fiscal_year=value_year) %>%
  ungroup() %>%
  # add company names
  left_join(companies_to_ein)
  

```

```{r}

companies_to_ein <- read_csv(here("data", "companies.csv")) %>%
  mutate(EIN = as.character(ein), organization_name = as.character(Company)) %>%
  select(EIN, organization_name)


endowment_data <- read_rds(here("data", 
                                "endowments_by_most_recent_filings.RDS"))
endowment_data$BeginningYearBalanceAmt <- as.numeric(as.character(endowment_data$BeginningYearBalanceAmt))
endowment_data$ContributionsAmt <- as.numeric(as.character(endowment_data$ContributionsAmt))
endowment_data$OtherExpendituresAmt <- as.numeric(as.character(endowment_data$OtherExpendituresAmt))
endowment_data$AdministrativeExpensesAmt <- as.numeric(as.character(endowment_data$AdministrativeExpensesAmt))
endowment_data$GrantsOrScholarshipsAmt <- as.numeric(as.character(endowment_data$GrantsOrScholarshipsAmt))
endowment_data$InvestmentEarningsOrLossesAmt <- as.numeric(as.character(endowment_data$InvestmentEarningsOrLossesAmt))
endowment_data$EndYearBalanceAmt <- as.numeric(as.character(endowment_data$EndYearBalanceAmt))
endowment_data$EndingBalanceAmt <- as.numeric(as.character(endowment_data$EndingBalanceAmt))
endowment_data$DonorAdvisedFundsVlEOYAmt <- as.numeric(as.character(endowment_data$DonorAdvisedFundsVlEOYAmt))
#endowment_data$EndowmentsHeldUnrelatedOrgInd <- as.numeric(as.character(endowment_data$EndowmentsHeldUnrelatedOrgInd))
#endowment_data$EndowmentsHeldRelatedOrgInd <- as.numeric(as.character(endowment_data$EndowmentsHeldRelatedOrgInd))
endowment_data$FundsAndOtherAccountsVlEOYAmt <- as.numeric(as.character(endowment_data$FundsAndOtherAccountsVlEOYAmt))




endowment_data <- endowment_data %>% 
  select(-c(EndowmentsHeldUnrelatedOrgInd, EndowmentsHeldRelatedOrgInd)) %>%
  pivot_longer(-c(EIN, fiscal_year),
               names_to = "variable_name") %>%
  left_join(companies_to_ein)

```



```{r, include= FALSE, eval =FALSE}
  
# function development scratch code

var <- "BeginningYearBalanceAmt"

eins_with_variable <- endowment_data %>%
  filter(variable_name == var) %>%
    group_by(EIN) %>%
    summarize(number_observations = sum(!is.na(value))) %>%
    filter(number_observations != 0) %>%
    pull(EIN)
  
  


endowment_data %>%
  filter(EIN %in% eins_with_variable & variable_name == var) %>%
  filter(EIN == "860367773") %>%
  group_by(EIN) %>%
  mutate(EIN_mean = mean(value,na.rm= TRUE)) %>%
  ungroup() %>%
  group_by(variable_name) %>%
  mutate(quantile_group = ntile(EIN_mean, n = 4)) %>%
  group_by(EIN) %>% 
  # make sure EIN has single quantile group
  mutate(quantile_group = sample(quantile_group,1)) %>%
  mutate(quantile_group_labels = factor(paste0("Quantile ", quantile_group))) %>%
  ggplot(aes(x = fiscal_year, y = value, group = EIN, color = EIN)) +
  geom_point() +
  geom_line() +
  facet_wrap(~fct_reorder(
    quantile_group_labels,
    .x = quantile_group), scales="free_y") +
  scale_y_continuous(labels = comma) +
  viridis::scale_color_viridis(option = "mako", discrete = TRUE ) +
  theme_bw() +
  labs(title = paste0("Change in ", var, " Over Time\n"),
       x = "Fiscal Year")+
  theme(plot.title = element_text(size = 16, hjust = .5, face="bold"),
        plot.subtitle = element_text(hjust = .5, face="italic"),
        axis.text.x = element_text(size = 13),
        axis.title = element_text(size = 16, face = "bold"),
        legend.position = "none")

```

```{r}

# this function splits the data into 4 groups based on the mean value for that EIN 
# and plots the variable over time, faceted by group
# this is to handle the fact that the values are on very different scales,
# so if we plot them all together, it masks any interesting trends
# dotted lines represent where there was a missing year between observations


# plot_variable <- function(var) {
#   
#   # get eins with at least one observation of the variable
#   eins_with_variable <- endowment_data %>%
#   filter(variable_name == var) %>%
#     group_by(EIN) %>%
#     summarize(number_observations = sum(!is.na(value))) %>%
#     filter(number_observations != 0) %>%
#     pull(EIN)
#   
#   # split into quantiles based on EIN mean
#   data <- endowment_data %>%
#       filter(EIN %in% eins_with_variable & variable_name == var) %>%
#       group_by(EIN) %>%
#       mutate(EIN_mean = mean(value,na.rm= TRUE)) %>%
#       ungroup() %>%
#       group_by(variable_name) %>%
#       mutate(quantile_group = ntile(EIN_mean, n = 4)) %>%
#       group_by(EIN) %>% 
#       # make sure EIN has single quantile group
#       mutate(quantile_group = max(quantile_group)) %>%
#       mutate(quantile_group_labels = factor(paste0("Quantile ", quantile_group))) %>%
#       mutate(organization_name = ifelse(is.na(organization_name),
#                                         "Not Available", 
#                                         organization_name)) %>%
#     ungroup()
#   
#   # data with no nas so we can connect the values wehre there was a missing year
#   # instead of just having no line connecting points from years on each side of the gap
#   data_no_nas <- data %>% filter(!is.na(value))
#   
#   data %>%
#     ggplot(aes(x = fiscal_year, y = value, color = EIN, label = organization_name)) +
#     geom_line(data = data_no_nas,
#               aes( 
#                   x = fiscal_year,
#                   y = value, group = EIN),
#               color = "darkgray",
#               linetype = "dotted") +
#     geom_point(size = .9) +
#     geom_line() +
#     facet_wrap(~fct_reorder(
#       quantile_group_labels,
#       .x = quantile_group), scales="free_y", ncol = 2) +
#     scale_y_continuous(labels = comma) +
#     scale_x_continuous(breaks = seq.int(2010, 2021, by =2)) +
#     viridis::scale_color_viridis(option = "mako", discrete = TRUE, end=.94) +
#     theme_bw() +
#     labs(title = paste0("Change in ", var, " Over Time"),
#          x = "Fiscal Year",
#          y = paste0("value of ", var)) +
#     theme(plot.title = element_text(size = 18, 
#                                     hjust = .5, face="bold",
#                                     margin =margin(.1,.1,10,.1)),
#           plot.subtitle = element_text(hjust = .5, face="italic"),
#           axis.text.x = element_text(size = 13),
#           axis.title = element_text(size = 13, face = "bold"),
#           legend.position = "none")
# }


# UPDATED TIME FRAME - TIME SERIES LINE GRAPH
plot_line <- function(var) {
  
  # get eins with at least one observation of the variable
  eins_with_variable <- endowment_data %>%
  filter(variable_name == var) %>%
    group_by(EIN) %>%
    summarize(number_observations = sum(!is.na(value))) %>%
    filter(number_observations != 0) %>%
    pull(EIN)

  # split into quantiles based on EIN mean
  data <- endowment_data %>%
      filter(EIN %in% eins_with_variable & variable_name == var) %>%
      group_by(EIN) %>%
      mutate(EIN_mean = mean(value,na.rm= TRUE)) %>%
      ungroup() %>%
      group_by(variable_name) %>%
      mutate(quantile_group = ntile(EIN_mean, n = 4)) %>%
      group_by(EIN) %>%
      # make sure EIN has single quantile group
      mutate(quantile_group = max(quantile_group)) %>%
      mutate(quantile_group_labels = factor(paste0("Quantile ", quantile_group))) %>%
      mutate(organization_name = ifelse(is.na(organization_name),
                                        "Not Available",
                                        organization_name)) %>%
    ungroup()

  
  data %>%
    ggplot(aes(x = fiscal_year, y = value, color = EIN, label = organization_name)) +
    geom_line(data = data_no_nas,
              aes(x = fiscal_year, y = value, group = EIN),
              color = "darkgray", linetype = "dotted") +
    geom_point(size = .9) +
    geom_line() +
    facet_wrap(~fct_reorder(quantile_group_labels, .x = quantile_group), scales = "free_y", ncol = 2) +
    scale_y_continuous(labels = scales::comma) +
    scale_x_continuous(breaks = seq(2012, 2022, by = 1), limits = c(2012, 2022)) +
    viridis::scale_color_viridis(option = "mako", discrete = TRUE, end = .94) +
    theme_bw() +
    labs(title = paste0("Change in ", var, " Over Time"),
         x = "Fiscal Year",
         y = paste0("Value of ", var)) +
    theme(plot.title = element_text(size = 18, hjust = .5, face = "bold", margin = margin(.1, .1, 10, .1)),
          plot.subtitle = element_text(hjust = .5, face = "italic"),
          axis.text.x = element_text(size = 13),
          axis.title = element_text(size = 13, face = "bold"),
          legend.position = "none")
}

```


```{r}
# BAR GRAPH W/ AVERAGE CHANGE
plot_variable_bar <- function(var) {
  
  # Get EINs with at least one observation of the variable
  eins_with_variable <- endowment_data %>%
    filter(variable_name == var) %>%
    group_by(EIN) %>%
    summarize(number_observations = sum(!is.na(value)), .groups = 'drop') %>%
    filter(number_observations != 0) %>%
    pull(EIN)
  
  # Split into quantiles based on EIN mean
  data <- endowment_data %>%
      filter(EIN %in% eins_with_variable & variable_name == var) %>%
      group_by(EIN) %>%
      mutate(EIN_mean = mean(value, na.rm = TRUE)) %>%
      ungroup() %>%
      group_by(variable_name) %>%
      mutate(quantile_group = ntile(EIN_mean, n = 4)) %>%
      group_by(EIN) %>%
      mutate(quantile_group = max(quantile_group)) %>%
      mutate(quantile_group_labels = factor(paste0("Quantile ", quantile_group))) %>%
      mutate(organization_name = ifelse(is.na(organization_name), "Not Available", organization_name)) %>%
      ungroup()

  # Facted bar graphs  
  data <- data %>%
    arrange(EIN, fiscal_year) %>%
    mutate(change = value - dplyr::lag(value)) %>%
    filter(!is.na(change))  # Remove NAs which result from the lag subtraction

  # Aggregate data by fiscal year and quantile group
  aggregated_data <- data %>%
    group_by(fiscal_year, quantile_group_labels) %>%
    summarize(mean_change = mean(change, na.rm = TRUE), .groups = 'drop')

  
  # Check if there is any data to plot before attempting to create the plot
if(any(table(aggregated_data$quantile_group_labels) > 0)) {
  ggplot(aggregated_data, aes(x = fiscal_year, y = mean_change, fill = quantile_group_labels)) +
    geom_col(position = "dodge") +
    facet_wrap(~fct_reorder(quantile_group_labels, .x = ntile(mean_change, n = 4)), scales = "free_y", ncol = 2) +
    
    scale_x_continuous(breaks = seq(2012, 2022, by = 1), limits = c(2012, 2022)) +
    scale_y_continuous(labels = scales::comma) +
    viridis::scale_fill_viridis(discrete = TRUE, option = "mako", end = .94) +
    theme_bw()
} else {
  cat("No data available for plotting\n")
}

}

```



# Bar Graphs of Average Changes

```{r, fig.width = 12, fig.height = 6}

# plot each variable over time
walk(unique(endowment_data$variable_name),
     ~{plt <- plot_variable_bar(.x) 
     print(plt)
     }
)

```


# Shiny Quantile List


```{r}
unique_variable_names_list <- c("BeginningYearBalanceAmt", "EndYearBalanceAmt",
                                "ContributionsAmt", "InvestmentEarningsOrLossesAmt",
                                "GrantsOrScholarshipsAmt", "OtherExpendituresAmt",
                                "AdministrativeExpensesAmt", "PrmnntEndowmentBalanceEOYPct",
                                "TermEndowmentBalanceEOYPct", "EndingBalanceAmt",
                                "BoardDesignatedBalanceEOYPct")

# Function to list companies by quantile for a given variable
list_companies_by_quantile_all <- function(data, var) {
  # Get EINs with at least one observation of the variable
  eins_with_variable <- data %>%
    filter(variable_name == var) %>%
    group_by(EIN) %>%
    summarize(number_observations = sum(!is.na(value)), .groups = 'drop') %>%
    filter(number_observations > 0) %>%
    pull(EIN)
  
  # Check if there are any EINs with observations
  if (length(eins_with_variable) == 0) {
    return(paste("No valid data found for variable:", var))
  }

  # Split into quantiles based on EIN mean
  quantile_data <- data %>%
    filter(EIN %in% eins_with_variable, variable_name == var) %>%
    group_by(EIN) %>%
    summarize(EIN_mean = mean(value, na.rm = TRUE), .groups = 'drop') %>%
    mutate(quantile_group = ntile(EIN_mean, 4)) %>%
    left_join(data %>% select(EIN, organization_name), by = "EIN") %>%
    distinct(EIN, .keep_all = TRUE) %>%
    select(organization_name, quantile_group) %>%
    arrange(quantile_group, organization_name)

  # Display in a table
  if (nrow(quantile_data) == 0) {
    return(paste("No quantile data available for variable:", var))
  }

  quantile_data %>%
    kable("html") %>%
    kable_styling("striped", full_width = FALSE) %>%
    column_spec(1, bold = TRUE) %>%
    pack_rows("Quantile 1", which(quantile_data$quantile_group == 1)[1], which(quantile_data$quantile_group == 1)[length(which(quantile_data$quantile_group == 1))], background = "#D3D3D3") %>%
    pack_rows("Quantile 2", which(quantile_data$quantile_group == 2)[1], which(quantile_data$quantile_group == 2)[length(which(quantile_data$quantile_group == 2))], background = "#ADD8E6") %>%
    pack_rows("Quantile 3", which(quantile_data$quantile_group == 3)[1], which(quantile_data$quantile_group == 3)[length(which(quantile_data$quantile_group == 3))], background = "#90EE90") %>%
    pack_rows("Quantile 4", which(quantile_data$quantile_group == 4)[1], which(quantile_data$quantile_group == 4)[length(which(quantile_data$quantile_group == 4))], background = "#FFB6C1")
}


```

```{r}

process_variable_safely <- function(var_name, data) {
  cat("Processing variable:", var_name, "\n")
  tryCatch({
    result <- list_companies_by_quantile_all(data, var_name)
    print(result)  # Print the result if successful
  }, error = function(e) {
    cat("Error processing variable", var_name, ": ", e$message, "\n")  # Print the error message
  })
}

# Use lapply to run the function for each variable name
result_tables <- lapply(unique_variable_names_list, function(var_name) {
  process_variable_safely(var_name, endowment_data)
})
```


# HTML Quantile List


```{r}
list_companies_by_quantile_html <- function(data, var) {
  # Get EINs with at least one observation of the variable
  eins_with_variable <- data %>%
    filter(variable_name == var) %>%
    group_by(EIN) %>%
    summarize(number_observations = sum(!is.na(value)), .groups = 'drop') %>%
    filter(number_observations > 0) %>%
    pull(EIN)

  # If no EINs, return a message
  if (length(eins_with_variable) == 0) {
    return(paste("No valid data found for variable:", var))
  }

  # Split into quantiles based on EIN mean
  quantile_data <- data %>%
    filter(EIN %in% eins_with_variable, variable_name == var) %>%
    group_by(EIN) %>%
    summarize(EIN_mean = mean(value, na.rm = TRUE), .groups = 'drop') %>%
    mutate(quantile_group = ntile(EIN_mean, 4)) %>%
    left_join(data %>% select(EIN, organization_name), by = "EIN") %>%
    distinct(EIN, .keep_all = TRUE) %>%
    select(organization_name, quantile_group) %>%
    arrange(quantile_group, organization_name)

  # Format and return the table
  table_output <- quantile_data %>%
    kable("html", escape = FALSE) %>%
    kable_styling("striped", full_width = F) %>%
    column_spec(1, bold = T) %>%
    scroll_box(width = "100%", height = "500px")

  return(htmltools::HTML(table_output))
}

# Processing function that prints results safely
process_variable_safely <- function(var_name, data) {
  cat("Processing variable:", var_name, "\n")
  tryCatch({
    result <- list_companies_by_quantile_html(data, var_name)
    print(result)  # Ensure it prints in Markdown
  }, error = function(e) {
    cat("Error processing variable", var_name, ": ", e$message, "\n")
  })
}

# Run the function for each variable and ensure output is handled
results <- lapply(unique_variable_names_list, function(var_name) {
  process_variable_safely(var_name, endowment_data)
})
```


# Quantile Lists

```{r}
list_companies_by_quantile_list <- function(data, var) {
  # Get EINs with at least one observation of the variable
  eins_with_variable <- data %>%
    filter(variable_name == var) %>%
    group_by(EIN) %>%
    summarize(number_observations = sum(!is.na(value)), .groups = 'drop') %>%
    filter(number_observations > 0) %>%
    pull(EIN)
  
  # If no EINs, return a message
  if (length(eins_with_variable) == 0) {
    return(paste("No valid data found for variable:", var))
  }

  # Split into quantiles based on EIN mean
  quantile_data <- data %>%
    filter(EIN %in% eins_with_variable, variable_name == var) %>%
    group_by(EIN) %>%
    summarize(EIN_mean = mean(value, na.rm = TRUE), .groups = 'drop') %>%
    mutate(quantile_group = ntile(EIN_mean, 4)) %>%
    left_join(data %>% select(EIN, organization_name), by = "EIN") %>%
    distinct(EIN, .keep_all = TRUE) %>%
    select(organization_name, quantile_group) %>%
    arrange(quantile_group, organization_name)

  # Return a list of names grouped by quantile
  quantile_groups <- split(quantile_data$organization_name, quantile_data$quantile_group)
  names(quantile_groups) <- paste("Quantile", names(quantile_groups))
  return(quantile_groups)
}


unique_variable_names_list <- c("BeginningYearBalanceAmt", "EndYearBalanceAmt",
                                "ContributionsAmt", "InvestmentEarningsOrLossesAmt",
                                "GrantsOrScholarshipsAmt", "OtherExpendituresAmt",
                                "AdministrativeExpensesAmt", "PrmnntEndowmentBalanceEOYPct",
                                "TermEndowmentBalanceEOYPct", "EndingBalanceAmt",
                                "BoardDesignatedBalanceEOYPct")

results <- lapply(unique_variable_names_list, function(var_name) {
  result <- list_companies_by_quantile_list(endowment_data, var_name)
  cat("Results for", var_name, ":\n")
  print(result)
})

```



